#spring:
#  security:
#    user:
#      name: user1
#      password: password1

logging:
  level:
    org.springframework.security: error
    com.example.springsecurityexample: debug
#    org.hibernate.type.descriptor.sql: trace

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
