#spring:
#  security:
#    user:
#      name: user1
#      password: password1

logging:
  level:
    org.springframework.security: debug
    com.example.springsecurityexample: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:
